### ISSUE TITLE
Какую библиотеку для telegram bot вы бы порекомендовали использовать?

### ISSUE THREAD

**Issue by jobman** [move-ton/ton-client-py#2]
Как я понял сдк асинхронная, и нужно использовать библиотеку которая поддерживает асинхронный режим работы? или в синхронном тоже можно?

**Comment by rymkapro** [comment]
Библиотека может работах как синхронно, так и асинхронно (аргумент `is_async` при создании объекта класса клиента)

Какую библиотеку выбрать для бота решать только вам
